export type ToolCategory = {
  id: string;
  title: string;
  usedFor: string;
  visual: string;
  softwareTools: string[];
  aiTools: string[];
};

export const categories: ToolCategory[] = [
  {
    id: "video-editing",
    title: "Video Editing UI/UX Designer",
    usedFor:
      "Storytelling, timeline editing, color grading, motion graphics, thumbnails, and social publishing workflows.",
    visual: "Video Production",
    softwareTools: [
      "Adobe Premiere Pro",
      "DaVinci Resolve",
      "Final Cut Pro",
      "After Effects",
      "CapCut Desktop",
      "Filmora",
      "Blender",
      "Adobe Audition",
      "Canva",
      "OBS Studio",
      "VLC Media Player",
      "Frame.io",
    ],
    aiTools: [
      "Runway",
      "Descript",
      "Topaz Video AI",
      "Adobe Firefly",
      "Pika",
      "VEED AI",
      "Synthesia",
      "HeyGen",
      "ElevenLabs",
      "Wisecut",
    ],
  },
  {
    id: "ui-ux",
    title: "UI/UX Designer",
    usedFor:
      "User research, wireframes, prototypes, design systems, usability testing, and handoff to development teams.",
    visual: "UI and UX Design",
    softwareTools: [
      "Figma",
      "Framer",
      "Adobe XD",
      "Sketch",
      "Miro",
      "InVision",
      "Zeplin",
      "Maze",
      "Hotjar",
      "Notion",
      "FigJam",
      "Balsamiq",
    ],
    aiTools: [
      "Uizard",
      "Galileo AI",
      "Visily AI",
      "Khroma",
      "Stark AI",
      "Attention Insight",
      "Magician for Figma",
      "Relume AI",
      "Diagram AI",
      "UX Pilot",
    ],
  },
  {
    id: "software-development",
    title: "Software Developer",
    usedFor:
      "Coding, debugging, testing, version control, API development, deployment, monitoring, and team collaboration.",
    visual: "Software Development",
    softwareTools: [
      "Visual Studio Code",
      "WebStorm",
      "Git",
      "GitHub",
      "Docker",
      "Postman",
      "Node.js",
      "npm",
      "Jira",
      "Linux Terminal",
      "Vercel",
      "Firebase",
    ],
    aiTools: [
      "GitHub Copilot",
      "ChatGPT",
      "Cursor",
      "Codeium",
      "Tabnine",
      "Amazon CodeWhisperer",
      "Sourcegraph Cody",
      "Phind",
      "CodiumAI",
      "Snyk AI",
    ],
  },
  {
    id: "researcher",
    title: "Software Researcher",
    usedFor:
      "Literature review, experiment planning, data analysis, reproducible workflows, and technical reporting.",
    visual: "Research Workflow",
    softwareTools: [
      "Google Scholar",
      "Semantic Scholar",
      "arXiv",
      "Zotero",
      "Mendeley",
      "Jupyter Notebook",
      "Python",
      "RStudio",
      "MATLAB",
      "SPSS",
      "Notion",
      "Overleaf",
    ],
    aiTools: [
      "Elicit",
      "Consensus",
      "Perplexity",
      "Scite Assistant",
      "Research Rabbit",
      "Connected Papers",
      "Scholarcy",
      "Iris.ai",
      "Paper Digest",
      "Wolfram Alpha",
    ],
  },
  {
    id: "game-development",
    title: "Game Developer",
    usedFor:
      "Gameplay programming, 2D/3D assets, level design, performance profiling, and shipping builds.",
    visual: "Game Development",
    softwareTools: [
      "Unity",
      "Unreal Engine",
      "Godot",
      "Visual Studio",
      "Blender",
      "Maya",
      "Substance Painter",
      "Aseprite",
      "FMOD Studio",
      "Wwise",
      "Steamworks",
      "Perforce",
    ],
    aiTools: [
      "Inworld AI",
      "Scenario",
      "Ludo.ai",
      "Leonardo AI",
      "Meshy",
      "Kaedim",
      "Promethean AI",
      "NVIDIA ACE",
      "Layer AI",
      "Charisma AI",
    ],
  },
  {
    id: "games",
    title: "Popular Games (Reference)",
    usedFor:
      "Benchmarking gameplay loops, UI patterns, and production quality standards.",
    visual: "Games Reference",
    softwareTools: [
      "Minecraft",
      "Grand Theft Auto V",
      "Fortnite",
      "PUBG: Battlegrounds",
      "Valorant",
      "Counter-Strike 2",
      "League of Legends",
      "Dota 2",
      "Elden Ring",
      "The Witcher 3",
      "Red Dead Redemption 2",
      "God of War Ragnarok",
      "Hades",
      "Hollow Knight",
      "Apex Legends",
      "Cyberpunk 2077",
    ],
    aiTools: [
      "NVIDIA DLSS",
      "AMD FSR",
      "NVIDIA Reflex",
      "GameGAN Research",
      "AI Director (Left 4 Dead style systems)",
      "Procedural NPC Behavior Models",
      "Voice NPC Pipelines (ElevenLabs)",
      "AI Matchmaking Services",
      "Anti-Cheat AI Systems",
      "Player Telemetry ML Dashboards",
    ],
  },
  {
    id: "civil-engineering",
    title: "Civil Engineering Software",
    usedFor: "Design, structural analysis, and construction planning.",
    visual: "Civil Engineering",
    softwareTools: [
      "AutoCAD",
      "STAAD Pro",
      "ETABS",
      "Revit",
      "SAP2000",
      "Primavera P6",
      "SketchUp",
      "Civil 3D",
      "ANSYS",
      "SAFE",
      "Tekla Structures",
      "MicroStation",
      "MS Project",
      "ArcGIS",
      "OpenRoads Designer",
    ],
    aiTools: [],
  },
  {
    id: "mechanical-engineering",
    title: "Mechanical Engineering Software",
    usedFor: "Machine design, simulation, and manufacturing workflows.",
    visual: "Mechanical Engineering",
    softwareTools: [
      "SolidWorks",
      "CATIA",
      "Fusion 360",
      "ANSYS",
      "MATLAB",
      "Creo",
      "NX Siemens",
      "AutoCAD",
      "Abaqus",
      "COMSOL Multiphysics",
      "Mastercam",
      "Solid Edge",
      "Inventor",
      "Simulink",
      "MSC Adams",
    ],
    aiTools: [],
  },
  {
    id: "electrical-engineering",
    title: "Electrical Engineering Software",
    usedFor: "Circuit design, power systems, and simulation.",
    visual: "Electrical Engineering",
    softwareTools: [
      "MATLAB",
      "Simulink",
      "ETAP",
      "PSCAD",
      "PSpice",
      "Multisim",
      "Proteus",
      "AutoCAD Electrical",
      "LabVIEW",
      "EasyEDA",
      "LTspice",
      "PowerWorld Simulator",
      "Altium Designer",
      "HOMER Pro",
    ],
    aiTools: [],
  },
  {
    id: "instrumentation-engineering",
    title: "Instrumentation Engineering Software",
    usedFor: "Automation, control systems, and industrial monitoring.",
    visual: "Instrumentation",
    softwareTools: [
      "LabVIEW",
      "MATLAB",
      "Simulink",
      "SCADA",
      "PLC Programming",
      "TIA Portal",
      "Wonderware",
      "Ignition SCADA",
      "ControlLogix",
      "FactoryTalk",
      "DCS",
      "NI Multisim",
    ],
    aiTools: [],
  },
  {
    id: "cs-software-engineering",
    title: "Computer Science / Software Engineering Tools",
    usedFor: "Development, deployment, and UI/UX product workflows.",
    visual: "Computer Science",
    softwareTools: [
      "Visual Studio Code",
      "GitHub",
      "Git",
      "Docker",
      "Kubernetes",
      "Postman",
      "Figma",
      "Adobe XD",
      "MongoDB",
      "MySQL",
      "Node.js",
      "React",
      "Next.js",
      "Firebase",
      "Jira",
    ],
    aiTools: [],
  },
];

export const officialLinks: Record<string, string> = {
  "Adobe Premiere Pro": "https://www.adobe.com/products/premiere.html",
  "DaVinci Resolve": "https://www.blackmagicdesign.com/products/davinciresolve",
  "Final Cut Pro": "https://www.apple.com/final-cut-pro/",
  "After Effects": "https://www.adobe.com/products/aftereffects.html",
  "Visual Studio Code": "https://code.visualstudio.com/",
  GitHub: "https://github.com/",
  Git: "https://git-scm.com/",
  Docker: "https://www.docker.com/",
  Figma: "https://www.figma.com/",
  "Node.js": "https://nodejs.org/",
  React: "https://react.dev/",
  "Next.js": "https://nextjs.org/",
  MATLAB: "https://www.mathworks.com/products/matlab.html",
  Simulink: "https://www.mathworks.com/products/simulink.html",
  AutoCAD: "https://www.autodesk.com/products/autocad/overview",
  Revit: "https://www.autodesk.com/products/revit/overview",
  "SolidWorks": "https://www.solidworks.com/",
  "Unreal Engine": "https://www.unrealengine.com/",
  Unity: "https://unity.com/",
};

export function getOfficialUrl(toolName: string) {
  return (
    officialLinks[toolName] ??
    `https://www.google.com/search?q=${encodeURIComponent(`${toolName} official`)}`
  );
}

export function getCategoryById(id: string) {
  return categories.find((category) => category.id === id) ?? null;
}
